version: "3"
services: 
  api:
    environment: 
      AUTH0_CALLBACK_URL: https://quizlet.jesspoemape.us/auth/callback
    build: .
    restart: always
    volumes: 
      - static:/srv/quizlet/build
  web: 
    ports: 
      - "80:80"
    environment: 
      VIRTUAL_HOST: quizlet.jesspoemape.us
      LETSENCRYPT_HOST: quizlet.jesspoemape.us
      LETSENCRYPT_EMAIL: jesspoemape@gmail.com
    image: nginx:alpine
    restart: always
    volumes: 
      - static:/srv/quizlet/build
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes: 
  static:
    driver: local